name: Build on Pull Request

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always() # kör alltid, även om build failar
    steps:
      - name: Send notification to Discord
        run: |
          STATUS="${{ needs.build.result }}"
          if [ "$STATUS" = "success" ]; then
            COLOR=3066993
            MESSAGE="✅ Build passed for PR #${{ github.event.pull_request.number }} by ${{ github.actor }}"
          else
            COLOR=15158332
            MESSAGE="❌ Build failed for PR #${{ github.event.pull_request.number }} by ${{ github.actor }}"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"embeds\":[{\"title\":\"GitHub Action Build Result\",\"description\":\"$MESSAGE\",\"color\":$COLOR}]}" \https://discordapp.com/api/webhooks/1415266268851736657/pkptSfn3GKbm6BydccQ4Fy_QWQ32jJaw1IrTCmmtT5_VX-EI5bLY9H0BN5MXnVP6Tofk